#!/bin/bash

#
# setclock - set Raspberry Pi clock using ntpdate
#
# 29Jun16  Added code to check uid
# 21Jun16  Everett Lipman
#

COMMAND="/usr/sbin/ntpdate -uv"
SERVER="ntp.ucsb.edu"
# SERVER="132.163.4.101"  # time-a.timefreq.bldrdoc.gov

if [ `id -u` -eq 0 ]
then
   $COMMAND $SERVER
else
   echo >&2
   echo "$0: this script must be run as root." >&2
   echo >&2
fi
